% -----------------------------------------------------------------
% Legacy exploratory analysis by a member of the Wilson Lab.
% Historical record only — not part of the bancpipeline release.
% -----------------------------------------------------------------

%% Script to load images generated by R and organized them into a single plot

% 1) get data directory and load data
% get figure directory
inputfigdir = [strrep( which("dn_anatomical_clusters_display.m"), ...
    ['analysis', filesep, 'matlab', filesep, 'dn_anatomical_clusters_display.m'], ''), ...
    'figures', filesep, 'dn_dist_1-9_plus_nt'];

if ~exist(inputfigdir, 'dir')
    mkdir(inputfigdir)
end

% predefine a cell array to hold the image filenames
inputimages = rdir([inputfigdir, filesep, '*_skt.png']);
inputimages = {inputimages.name}';

% sort figures in ascending order
fig_index = strrep(inputimages, [inputfigdir, filesep], '');
fig_index = strrep(fig_index, 'DN_nblast_clus_', '');
fig_index = strrep(fig_index, '_skt.png', '');
fig_index = cellfun(@str2double, fig_index);
[~, neworder] = sort(fig_index, 'ascend');

inputimages = inputimages(neworder);

figH = figure('Position', [100 100 2400 1200]);

% loop over each image
for i = 1:numel(inputimages)
   
    % read each image
    img = imread(inputimages{i});
    
    axH(i) = subplot(3, 10, i);
    imshow(img);
    
    title(sprintf('Anatomical cluster %d', i));

end

width2use = (1-0.02)/10;
height2use = (1-0.02)/3;

axhidx = {1:10, 11:20, 21:30};
row2use = [1, 2, 3];

for i = 1:numel(axhidx)
    for ii = 1:numel(axhidx{i})
        axH(axhidx{i}(ii)).Position = [0.01 + (ii - 1)*width2use, 0.01 + height2use*(3 - row2use(i)), width2use*0.95, height2use];
    end
end

saveas(figH, [inputfigdir, filesep, 'DN_clusters_all.png'])
close(figH)