% -----------------------------------------------------------------
% Legacy exploratory analysis by a member of the Wilson Lab.
% Historical record only — not part of the bancpipeline release.
% -----------------------------------------------------------------

function plot_heatmap_syn_per_np(syn_per_np, type_name, np_names, ...
    zscale, vnc_nom2use, figname, figdirectory)
% plot_heatmap_syn_per_np: function to plot heatmaps cosine distances
%
% Usage:
%   plot_heatmap_syn_per_np(syn_per_np, type_name, np_names, 
%       zscale, vnc_nom2use, figname, figdirectory)
%
% Args:
%   syn_per_np: matrix of synapses per neuropil
%   type_name: name of dn type
%   np_names: neuropil names
%   zscale: scale to use for input distance matrix
%   vnc_nom2use: choose vnc neuropils to use
%   figname: figure name
%   figdirectory: target directory

% default order of neuropils
%   Note: for VNC neuropils;
%       v_COURT refers to Court et al 2020
%       V_MANC refers to the nomencleture adopted in Takemura et al 2024

if strcmp(vnc_nom2use, 'court')
    np_vnc = { ...                            % Tectulum
        'v_COURT_vnc_NTct', ...                % Neck tectulum
        'v_COURT_vnc_WTct', ...                % Wing tectulum
        'v_COURT_vnc_HTct', ...                % Haltere tectulum
        'v_COURT_vnc_IntTct', ...              % Intermediate tectulum
        'v_COURT_vnc_LTct', ...                 % Lower tectulum
        ...                                            % Leg neuropil
        'v_COURT_vnc_ProNM_T1', ...        % Prothoracic neuromere
        'v_COURT_vnc_MesoNM_T2', ...     % Mesothoracic neuromere
        'v_COURT_vnc_MetaNM_T3', ...     % Metathoracic neuromere
        'v_COURT_vnc_mVAC', ...              % Medial Ventral association center
        'v_COURT_vnc_AMNP', ...              % Accessory Mesothoracic neuropil
        'v_COURT_vnc_ABDNM', ...            % Abdominal Neuromere (ANm)
        };
elseif strcmp(vnc_nom2use, 'manc')
    np_vnc = { ...                              % Extra domain
        'v_MANC_vnc_cervical_connective', ... 
        ...                                            % Tectulum
        'v_MANC_vnc_NTct_UTct_T1_L', ...    % Neck tectulum
        'v_MANC_vnc_NTct_UTct_T1_R', ...
        'v_MANC_vnc_WTct_UTct_T2_L', ...   % Wing tectulum
        'v_MANC_vnc_WTct_UTct_T2_R', ...
        'v_MANC_vnc_HTct_UTct_T3_L', ...    % Haltere tectulum
        'v_MANC_vnc_HTct_UTct_T3_R', ...
        'v_MANC_vnc_IntTct', ...                    % Intermediate tectulum
        'v_MANC_vnc_LTct', ...                      % Lower tectulum
        ...                                            % Leg neuropil
        'v_MANC_vnc_LNp_T1_L', ...        % Prothoracic neuromere
        'v_MANC_vnc_LNp_T1_R', ...
        'v_MANC_vnc_LNp_T2_L', ...        % Mesothoracic neuromere
        'v_MANC_vnc_LNp_T2_R', ...
        'v_MANC_vnc_LNp_T3_L', ...        % Metathoracic neuromere
        'v_MANC_vnc_LNp_T3_R', ...
        'v_MANC_vnc_mVAC_T1_L', ...            % Medial Ventral association center
        'v_MANC_vnc_mVAC_T1_R', ...
        'v_MANC_vnc_mVAC_T2_L', ...
        'v_MANC_vnc_mVAC_T2_R', ...
        'v_MANC_vnc_mVAC_T3_L', ...
        'v_MANC_vnc_mVAC_T3_R', ...
        'v_MANC_vnc_LNp_T2_R', ...
        'v_MANC_vnc_AMNp_L', ...            % Accessory Mesothoracic neuropil
        'v_MANC_vnc_AMNp_R', ...
        'v_MANC_vnc_ANm', ...               % Abdominal Neuromere (ANm)
        };
end

np_brain = { ...
    'b_ITO_midbrain_AMMC_L', ...
    'b_ITO_midbrain_AMMC_R', ...
    'b_ITO_midbrain_SAD', ...
    'b_ITO_midbrain_GNG', ...
    'b_ITO_midbrain_WED_L', ...
    'b_ITO_midbrain_WED_R', ...
    'b_ITO_midbrain_AVLP_L', ...
    'b_ITO_midbrain_AVLP_R', ...
    'b_ITO_optic_ME_L', ...
    'b_ITO_optic_ME_R', ...
    'b_ITO_optic_AME_L', ...
    'b_ITO_optic_AME_R', ...
    'b_ITO_optic_LO_L', ...
    'b_ITO_optic_LO_R', ...
    'b_ITO_optic_LOP_L', ...
    'b_ITO_optic_LOP_R', ...
    'b_ITO_midbrain_PVLP_L', ...
    'b_ITO_midbrain_PVLP_R', ...
    'b_ITO_midbrain_PLP_L', ...
    'b_ITO_midbrain_PLP_R', ...
    'b_ITO_midbrain_AOTU_L', ...
    'b_ITO_midbrain_AOTU_R', ...
    'b_ITO_midbrain_AL_L', ...
    'b_ITO_midbrain_AL_R', ...
    'b_ITO_midbrain_MB_VL_L', ...
    'b_ITO_midbrain_MB_VL_R', ...
    'b_ITO_midbrain_MB_ML_L', ...
    'b_ITO_midbrain_MB_ML_R', ...
    'b_ITO_midbrain_MB_PED_L', ...
    'b_ITO_midbrain_MB_PED_R', ...
    'b_ITO_midbrain_MB_CA_L', ...
    'b_ITO_midbrain_MB_CA_R', ...
    'b_ITO_midbrain_LH_L', ...
    'b_ITO_midbrain_LH_R', ...
    'b_ITO_midbrain_EB', ...
    'b_ITO_midbrain_FB', ...
    'b_ITO_midbrain_PB', ...
    'b_ITO_midbrain_NO', ...
    'b_ITO_midbrain_BU_L', ...
    'b_ITO_midbrain_BU_R', ...
    'b_ITO_midbrain_LAL_L', ...
    'b_ITO_midbrain_LAL_R', ...
    'b_ITO_midbrain_SLP_L', ...
    'b_ITO_midbrain_SLP_R', ...
    'b_ITO_midbrain_SIP_L', ...
    'b_ITO_midbrain_SIP_R', ...
    'b_ITO_midbrain_SMP_L', ...
    'b_ITO_midbrain_SMP_R', ...
    'b_ITO_midbrain_CRE_L', ...
    'b_ITO_midbrain_CRE_R', ...
    'b_ITO_midbrain_SCL_L', ...
    'b_ITO_midbrain_SCL_R', ...
    'b_ITO_midbrain_ICL_L', ...
    'b_ITO_midbrain_ICL_R', ...
    'b_ITO_midbrain_IB_L', ...
    'b_ITO_midbrain_IB_R', ...
    'b_ITO_midbrain_ATL_L', ...
    'b_ITO_midbrain_ATL_R', ...
    'b_ITO_midbrain_VES_L', ...
    'b_ITO_midbrain_VES_R', ...
    'b_ITO_midbrain_EPA_L', ...
    'b_ITO_midbrain_EPA_R', ...
    'b_ITO_midbrain_GOR_L', ...
    'b_ITO_midbrain_GOR_R', ...
    'b_ITO_midbrain_SPS_L', ...
    'b_ITO_midbrain_SPS_R', ...
    'b_ITO_midbrain_IPS_L', ...
    'b_ITO_midbrain_IPS_R', ...
    'b_ITO_midbrain_FLA_L', ...
    'b_ITO_midbrain_FLA_R', ...
    'b_ITO_midbrain_CAN_L', ...
    'b_ITO_midbrain_CAN_R', ...
    'b_ITO_midbrain_PRW', ...
    };

np_order = [np_vnc, np_brain];

% set default settings
if strcmp(zscale, 'log10')
    syn_per_np = log10(syn_per_np);
    icaxis = {[], [0 3], [0 3]};
    colorbarstr = {[], [], 'synapse count',};
    colorbarticks = {[], [], log10([1 10 100 1000])};
    colobarticklabels = {[], [], {'1', '10', '10^2', '10^3'}};
else
    icaxis = {[], [], [],  []};
    colorbarstr = {[], [], 'synapse count',};
    colorbarticks = {[], [], []};
    colobarticklabels = {[], [], []};
end

% generate YTicks for cluster heatmap
[type_name, sort_idx] = sort(type_name, 'descend');
syn_per_np = syn_per_np(sort_idx, :);

% generate colormaps
colormap_cos_dist = colorGradient(rgb('blue'), rgb('white'), 254);
colormap_clus = prism(length(type_name));

% match and order neuropils
[~, brain_np_idx] = ismember(np_order, np_names);
% remove names not matched
brain_np_idx(brain_np_idx == 0) = [];
np_names = np_names(brain_np_idx);
syn_per_np = syn_per_np(:, brain_np_idx);

% split neuropils in vnc vs brain
vnc_idx = contains(np_names, 'v_');
brain_idx = contains(np_names, 'b_');

% simplify names
np_names(vnc_idx) = strrep(np_names(vnc_idx), 'v_COURT_vnc_', '');
np_names(vnc_idx) = strrep(np_names(vnc_idx), 'v_MANC_vnc_', '');
np_names(brain_idx) = strrep(np_names(brain_idx), 'b_ITO_midbrain_', '');
np_names(brain_idx) = strrep(np_names(brain_idx), 'b_ITO_optic_', '');

np_names = strrep(np_names, '_', '-');

imatrix = {type_name, syn_per_np(:, vnc_idx), syn_per_np(:, brain_idx)};
yvars = {1:length(type_name), [], []};
icolormap = {colormap_clus, colormap_cos_dist, colormap_cos_dist};
xlabels = {[], np_names(vnc_idx), np_names(brain_idx)};
xlabelstitle = {[], 'vnc neuropils', 'brain neuropils'};

figH = figure('Position', [100 100 1300 450]);

for i = 1:numel(imatrix)
    
    axH(i) = subplot(1, 3, i);

    if ~isempty(yvars{i})
        imagesc(1, yvars{i}, imatrix{i})
    else
        imagesc(imatrix{i})
    end

    % set colormap
    colormap(axH(i), icolormap{i})
    if ~isempty(icaxis{i})
        caxis(axH(i), icaxis{i});
    end
    
    % add colorbar
    if ~isempty(colorbarstr{i})
        cbarH(i) = colorbar;
        cbarH(i).Label.String = colorbarstr{i};
        if ~isempty(colorbarticks{i})
            cbarH(i).Ticks = colorbarticks{i};
        end
    if ~isempty(colobarticklabels{i})
        cbarH(i).TickLabels = colobarticklabels{i};
    end
    end

    if ~isempty(yvars{i})
        axH(i).YTick = sort(sort_idx);
        axH(i).YTickLabel = chunk2cell(type_name, 1);
        axH(i).XTick = [];
        axH(i).YLabel.String = ['anatomical clusters (1-', num2str(max(type_name)), ')'];
    else
        axH(i).XTick = 1:length(xlabels{i});
        axH(i).XTickLabel = xlabels{i};
        axH(i).XTickLabelRotation = 45;
        axH(i).YTick = [];
        axH(i).XLabel.String = xlabelstitle{i};
    end

    axH(i).XAxisLocation = 'top';

end

% scale length 
width_scale = [sum(vnc_idx) sum(brain_idx)];
width_scale = width_scale/sum(width_scale);
fullwidth = 0.9;

% edit panel sizes
axH(1).Position = [0.03 0.1 0.01 0.6];
axH(2).Position = [0.05 0.1 fullwidth*width_scale(1) 0.6];
axH(3).Position = [fullwidth*width_scale(1) + axH(2).Position(1)*1.1 0.1 fullwidth*width_scale(2) 0.6];

% edit size of colorbar
cbarH(3).Position = [0.958 0.3 0.01 0.15];

figname = [figdirectory, filesep, figname];
saveas(figH, [figname, '.fig'])
saveas(figH, [figname, '.png'])
close(figH)

end